"""
panel_adapters.py
-----------------
One uniform interface per voter. Everything returns list[Span].

Two rules that make the comparison fair, and that you should state on the slide:

1. EVERY generative voter gets the BYTE-IDENTICAL prompt and schema. If you tune
   the prompt per model you are no longer comparing models, you are comparing
   your prompt-engineering effort per model, which nobody can reproduce.

2. NO model supplies character offsets. Models return verbatim quotes; Python
   locates them. This is the same grounding rule as workshop notebook 06, and it
   is what makes a hallucinated span detectable rather than merely wrong.

Self-preference: Panickssery, Bowman & Feng (NeurIPS 2024) show LLM evaluators
favour their own generations. If any holdout passage was generated by a model on
the panel, record it and exclude that model from voting on those passages.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
from dataclasses import dataclass
from typing import Callable, Protocol

from spanpanel import Span

# --------------------------------------------------------------------------
# the one prompt, shared by every generative voter
# --------------------------------------------------------------------------

PROMPT_VERSION = "sh2026-panel-v2"

SYSTEM = (
    "You annotate spatial expressions in historical and testimonial prose. "
    "You return only JSON matching the given schema. You never paraphrase: "
    "every quote must appear verbatim in the passage."
)

INSTRUCTION = """Mark every spatial expression in the passage below.

Labels:
  TOPONYM   a named place (Penrith, Auschwitz, the Adriatic)
  GEONOUN   an unnamed geographical or built feature (road, lake, camp, station)
  RELATION  a spatial relation or direction (beyond the river, north of, on our left)
  DISTANCE  a distance or nearness expression (about six miles distant, an hour away)
  TIME      a date, duration or temporal anchor (in 1943, the next morning, before dawn)

Rules:
  - Quote each expression EXACTLY as it appears. Do not normalise spelling.
    "Ulleswater" stays "Ulleswater".
  - Do not supply character positions. Quotes only.
  - Mark the longest defensible extent of each expression.
  - If there are none, return an empty list.

Return JSON: {"spans": [{"quote": "...", "label": "..."}]}

Passage:
<<<
%s
>>>"""

SCHEMA = {
    "type": "object",
    "properties": {
        "spans": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "quote": {"type": "string"},
                    "label": {"type": "string",
                              "enum": ["TOPONYM", "GEONOUN", "RELATION", "DISTANCE", "TIME"]},
                },
                "required": ["quote", "label"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["spans"],
    "additionalProperties": False,
}


def prompt_fingerprint() -> str:
    """Goes in the reproducibility record. Proves every voter saw the same text."""
    blob = (PROMPT_VERSION + SYSTEM + INSTRUCTION + json.dumps(SCHEMA, sort_keys=True))
    return hashlib.sha256(blob.encode()).hexdigest()[:16]


# --------------------------------------------------------------------------
# grounding: quotes -> offsets, computed locally
# --------------------------------------------------------------------------

def ground(passage: str, passage_id: str, quotes: list[dict], voter: str
           ) -> tuple[list[Span], list[dict]]:
    """Locate each quote in the passage. Returns (grounded spans, failures).

    Failures are kept, not silently dropped: the rate at which a voter quotes
    text that is not there is a reportable property of that voter, and it is one
    of the more interesting things this whole exercise measures.
    """
    spans, failures = [], []

    # Occurrences consumed PER DISTINCT QUOTE STRING, not globally.
    #
    # An earlier version tracked one global list of consumed character regions,
    # which was wrong. Models legitimately propose nested or overlapping spans:
    # "From Penrith" and "Penrith", or "the Eamont" and "Eamont". The longer
    # phrase claimed the region and the shorter one was then rejected as
    # "repeated_and_exhausted", so five of six correct spans were thrown away
    # and it looked like the model had missed Penrith entirely.
    #
    # The check only ever needed to stop the SAME quote mapping twice to the
    # same occurrence. Different quotes must not block each other.
    used_per_quote: dict[str, set[int]] = {}

    for q in quotes:
        quote, label = q.get("quote", ""), q.get("label", "")
        if not quote:
            failures.append({"voter": voter, "reason": "empty_quote", **q})
            continue
        taken = used_per_quote.setdefault(quote, set())
        start = -1
        for m in re.finditer(re.escape(quote), passage):
            if m.start() not in taken:
                start = m.start()
                break
        if start < 0:
            reason = "repeated_and_exhausted" if quote in passage else "not_in_passage"
            failures.append({"voter": voter, "reason": reason, **q})
            continue
        taken.add(start)
        spans.append(Span(passage_id, start, len(quote) + start, label, quote, voter))
    return spans, failures


# --------------------------------------------------------------------------
# voter protocol
# --------------------------------------------------------------------------

class Voter(Protocol):
    name: str
    kind: str          # "generative" | "supervised" | "deterministic"
    revision: str      # exact snapshot / model revision / resource version

    def annotate(self, passage: str, passage_id: str) -> tuple[list[Span], list[dict]]: ...


@dataclass
class GenerativeVoter:
    """Wraps any chat completion callable. Supply `call` per provider.

    `call(system, user, schema) -> str` must return the raw JSON text.
    Keep temperature at 0 and record it. Run each voter `n_runs` times if you
    want stability figures; one run cannot support a ranking.
    """
    name: str
    revision: str
    call: Callable[[str, str, dict], str]
    kind: str = "generative"
    max_retries: int = 3

    def annotate(self, passage: str, passage_id: str):
        last = None
        for attempt in range(self.max_retries):
            try:
                raw = self.call(SYSTEM, INSTRUCTION % passage, SCHEMA)
                data = json.loads(_strip_fences(raw))
                return ground(passage, passage_id, data.get("spans", []), self.name)
            except Exception as exc:                      # noqa: BLE001
                last = exc
                time.sleep(1.5 * (attempt + 1))
        return [], [{"voter": self.name, "reason": "unrecoverable",
                     "error": repr(last)}]


def _strip_fences(s: str) -> str:
    s = s.strip()
    if s.startswith("```"):
        s = re.sub(r"^```[a-zA-Z]*\n?", "", s)
        s = re.sub(r"\n?```$", "", s)
    return s.strip()


@dataclass
class CallableVoter:
    """Wraps spaCy, the pinned HF NER model, or the rule annotator.

    `fn(passage) -> list[dict]` with keys text/label/start_char/end_char.
    These voters already produce offsets, so no grounding step is needed, but
    they go through the same Span type so the aggregation cannot tell them apart.
    """
    name: str
    revision: str
    fn: Callable[[str], list[dict]]
    kind: str = "supervised"

    def annotate(self, passage: str, passage_id: str):
        out = []
        for d in self.fn(passage):
            out.append(Span(passage_id, d["start_char"], d["end_char"],
                            d["label"], d.get("text", ""), self.name))
        return out, []


# --------------------------------------------------------------------------
# panel runner
# --------------------------------------------------------------------------

def run_panel(voters: list, passages: dict[str, str], out_path: str,
              resume: bool = True) -> dict:
    """Run every voter over every passage, writing incrementally.

    Incremental writes matter: a panel run is the one part of this that costs
    money and wall-clock, and losing it to an exception at passage 380 of 400
    would be painful.
    """
    done: set[tuple[str, str]] = set()
    if resume and os.path.exists(out_path):
        with open(out_path, encoding="utf-8") as f:
            for line in f:
                r = json.loads(line)
                done.add((r["voter"], r["passage_id"]))

    failures: list[dict] = []
    with open(out_path, "a", encoding="utf-8") as f:
        for pid, text in passages.items():
            for v in voters:
                if (v.name, pid) in done:
                    continue
                t0 = time.time()
                spans, fails = v.annotate(text, pid)
                failures.extend(fails)
                served = dict(getattr(v, "call", None).last_meta) \
                    if hasattr(getattr(v, "call", None), "last_meta") else {}
                f.write(json.dumps({
                    "voter": v.name, "kind": v.kind, "revision": v.revision,
                    "passage_id": pid, "elapsed_s": round(time.time() - t0, 4),
                    "prompt_fingerprint": prompt_fingerprint(),
                    # what ACTUALLY served this call. With an aggregator the slug
                    # is a request, not a record; this is the record.
                    "served": served,
                    "spans": [{"start": s.start, "end": s.end,
                               "label": s.label, "text": s.text} for s in spans],
                    "n_failed_quotes": len(fails),
                    # PERSIST THE REJECTED STRINGS, not just the count. A quote
                    # that could not be located is the single most diagnostic
                    # artefact a voter produces, and keeping only a tally makes
                    # the reason unrecoverable after the run.
                    "failed_quotes": fails,
                }, ensure_ascii=False) + "\n")
                f.flush()

    return {"failures": failures, "n_failures": len(failures),
            "prompt_fingerprint": prompt_fingerprint()}


def load_panel_output(path: str) -> dict[str, list[Span]]:
    """Read a panel run back into the {voter: [Span]} shape cluster_spans wants."""
    by_voter: dict[str, list[Span]] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            by_voter.setdefault(r["voter"], []).extend(
                Span(r["passage_id"], s["start"], s["end"], s["label"],
                     s["text"], r["voter"]) for s in r["spans"]
            )
    return by_voter
